### ISSUE TITLE
Auto-publish CEPs on conda.org

### ISSUE THREAD

**Issue by jezdez** [conda/conda-dot-org#204]
## Description

Since CEPs are an important part for evolving conda community standards, I wonder if it would make sense to have a first class section under conda.org/ceps to render them fully automatically during build time?

## Tasks

- [ ] Find out how we can fetch CEP files from the `conda/ceps` repo
- [ ] Render a landing page under conda.org/ceps with a list of CEPs
- [ ] Show the CEPs in the left sidebar for easier selection

**Comment by jezdez** [comment]
Fixed in #220 and #222. /cc @jaimergp
